# Generated by Django 5.1.6 on 2025-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                default="usd",
                help_text="Укажите валюту в формате ISO 4217 (напр.: 'USD')",
                max_length=3,
                verbose_name="Валюта",
            ),
            preserve_default=False,
        ),
    ]
