# Generated by Django 5.1.6 on 2025-03-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_order_items_order_total_price_alter_item_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
