# Generated by Django 5.1.6 on 2025-03-01 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_discount_tax_order_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name": "Скидка", "verbose_name_plural": "Скидка"},
        ),
        migrations.AlterField(
            model_name="discount",
            name="percent_off",
            field=models.IntegerField(
                help_text="Укажите скидку в процентах",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Скидка",
            ),
        ),
    ]
