# Generated by Django 5.1.6 on 2025-03-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_alter_discount_options_alter_discount_percent_off"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.AddField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(null=True, to="items.discount"),
        ),
    ]
