# Generated by Django 5.1.6 on 2025-03-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_remove_order_discount_order_discounts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name": "Налоги", "verbose_name_plural": "Налоги"},
        ),
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.tax",
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="percentage",
            field=models.IntegerField(
                default=10, help_text="Укажите налог в процентах", verbose_name="Налог"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                help_text="Укажите валюту в формате ISO 4217 (напр.: 'usd')",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(to="items.discount"),
        ),
    ]
