# Generated by Django 5.1.6 on 2025-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_alter_item_options_alter_tax_options_order_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="name",
            field=models.CharField(
                default="test_tax", max_length=100, verbose_name="Название"
            ),
            preserve_default=False,
        ),
    ]
