# Generated by Django 5.1.6 on 2025-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0009_tax_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                default="usd",
                help_text="Укажите валюту в формате ISO 4217 (напр.: 'usd')",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
